### ISSUE TITLE
Add support for more textual format presets

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#11]
There are few MML formats I miss that aren't supported here:

- Sega Mega Drive XPMCKC 
- Sharp X68000 MDX NOTE.X
- Sharp X1 NRTDRV 
- FMDrive VST's own text format
- alternate version of PMD with three digit parameters
[mmltexts.zip](https://github.com/rerrahkr/YM2608-Tone-Editor/files/5178431/mmltexts.zip) - samples

**Comment by rerrahkr** [comment]
Thanks for your request.

#### XPMCK
- Import: can't prepare a preset since the order of the parameters is not fixed.
- Export: This app doesn't support DT expression using negative value.

#### FMDrive VST
I don't know the detailed format because I can't confirm the behavior of FMDrive VST without buying.

#### PMD alternate format
It's already support as far as I test.

#### Some X68000 drivers
It used to support NRTDRV and others, but I removed them from the default presets because the parameters of OPN and OPM match not completely.

---

I prepared only the format that seems to have many users. I think this is enough, as the user can add in formats that are not supported by default.

**Comment by freq-mod** [comment]
Oh, I see. Thanks for reply, nevertheless.

>This app doesn't support DT expression using negative value.

Would it be possible to add option to display DT value as signed while editing like in BT?
