### ISSUE TITLE
[Feature] - Extract instruments from PMD .M/.M2 file

### ISSUE THREAD

**Issue by rerrahkr** [rerrahkr/YM2608-Tone-Editor#19]
This is a very vague plan. I need to check PMD format to see if I can achieve this.

**Comment by OPNA2608** [comment]
I think it's doable to some degree. There are some very old versions of PMD modules where this code doesn't apply but awhile ago I hacked something together which sort-of worked: https://github.com/OPNA2608/libopenpmd/blob/436af496988b909b57694d12165a941996b2fb20/src/tools/pmd_instrip.c#L122-L179

- `0x0000` needs to be `0x00` for PC-98 platform, otherwise the next pointer is most likely wrong. (not investigated much)
- `0x0019` has a short with an offset relative to the platform byte (add +1 for absolute offset in file) to the instrument definitions section.
- The instrument definitions section is a list of `instrument ID -> register data` mappings. The format of the latter is equivalent to the .FF file format's register data (just the register stuff, without the instrument name). This list is terminated by a `0xFF00` short. (Or `0x00` ID + `0xFF` first register value if you want to detect it that way)

**Comment by rerrahkr** [comment]
Added at c49475c, thank you for your information!
